name: gimnazija-local

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik_local.yml:/etc/traefik/traefik.yml"

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
      target: dev-local
    env_file: ./dashboard/.env
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`api.gimnazija.local`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
    ports:
      - "1337:1337"

  db:
    image: postgres:17.2-alpine
    ports:
      - "5436:5432"
    env_file:
      - ./dashboard/.env
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      target: dev-local
    ports:
      - "3001:3001"
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - PUBLIC_GMNZ_API_URL=http://dashboard:1337
    env_file: ./web/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`gimnazija.local`)"
      - "traefik.http.routers.web.entrypoints=web"
    develop:
      watch:
        - action: rebuild
          path: ./web/package.json
          target: /app/fe
        - action: sync
          path: ./web
          target: /app/fe
          ignore:
            - ./web/node_modules/
            - ./web/build/


volumes:
  db-data: