services:
  api:
    build:
      context: ./api
      target: ${API_ENV-local}
    ports:
      - "${API_PORT}:${API_PORT}"
      # delve debugger
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    # volumes:
    #   - ./api:/app
    environment:
      - GOOGLE_OAUTH_SECRET=${GOOGLE_OAUTH_SECRET}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - API_PORT=${API_PORT}
      - SESSION_KEY=${SESSION_KEY}
      - VALID_EMAILS=${VALID_EMAILS}
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

  db:
    image: postgres:17.2-alpine
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      target: dev-local
    ports:
      - "3001:3001"
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - PUBLIC_GMNZ_API_URL=http://api:${API_PORT}
    env_file: ./web/.env
    develop:
      watch:
        - action: rebuild
          path: ./web/package.json
          target: /app/fe
        - action: sync
          path: ./web
          target: /app/fe
          ignore:
            - ./web/node_modules/
            - ./web/build/


volumes:
  db-data:
