services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    command:
      # HTTP to HTTPS global redirection
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      # Dynamic configuration file for certs
      - "--providers.file.filename=/etc/traefik/dynamic/certs-config.yaml"
      # Docker configuration
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOST_HOME_DIR}/traefik/certs-config.yaml:/etc/traefik/dynamic/certs-config.yaml:ro
      - ${HOST_HOME_DIR}/traefik/certs:/etc/certs:ro

  dashboard:
    container_name: dashboard
    image: ghcr.io/kapobajza/gimnazija_api:prod
    env_file: ./dashboard/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.softwhere.work`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.api.loadbalancer.server.port=1337"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://gimnazija.softwhere.work"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"
    ports:
      - "1337:1337"
    volumes:
      - dashboard-uploads:/app/dashboard/dist/build/uploads

  db:
    container_name: db
    image: mysql:9.1.0
    env_file:
      - ./dashboard/.env
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    container_name: web
    image: ghcr.io/kapobajza/gimnazija_web:prod
    ports:
      - "3000"
    environment:
      - HOST=0.0.0.0
    env_file: ./web/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`gimnazija.softwhere.work`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.services.web.loadbalancer.server.port=3000"


volumes:
  db-data:
  dashboard-uploads: