services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik_local.yml:/etc/traefik/traefik.yml"

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
      target: production
    env_file: ./dashboard/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`api.gimnazija.local`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
    platform: linux/amd64
    ports:
      - "1337:1337"

  db:
    image: mysql:9.1.0
    env_file:
      - ./dashboard/.env
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      target: production
    platform: linux/amd64
    ports:
      - "3000"
    environment:
      - HOST=0.0.0.0
    env_file: ./web/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`gimnazija.local`)"
      - "traefik.http.routers.web.entrypoints=web"
    develop:
      watch:
        - action: rebuild
          path: ./web/package.json
          target: /app/fe
        - action: sync
          path: ./web
          target: /app/fe
          ignore:
            - ./web/node_modules/
            - ./web/build/


volumes:
  db-data: