services:
  traefik:
    image: traefik:v3.1
    restart: unless-stopped
    command:
      # HTTP to HTTPS global redirection
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      # Dynamic configuration file for certs
      - "--providers.file.filename=/etc/traefik/dynamic/certs-config.yaml"
      # Docker configuration
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /traefik/certs-config.yaml:/etc/traefik/dynamic/certs-config.yaml:ro
      - /traefik/certs:/etc/certs:ro

  dashboard:
    image: ghcr.io/kapobajza/gimnazija_api:${GIT_COMMIT_HASH-prod}
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.gimnazija-bug.ba`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.api.loadbalancer.server.port=1337"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT"
      - "traefik.http.middlewares.testheader.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://gimnazija-bug.ba"
      - "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.testheader.headers.addvaryheader=true"
    ports:
      - "1337:1337"
    volumes:
      - dashboard-uploads:/app/dashboard/public/uploads
    secrets:
      - dashboard_jwt_secret
      - dashboard_app_keys
      - dashboard_api_token_salt
      - dashboard_admin_jwt_secret
      - dashboard_transfer_token_salt
      - database_password
    deploy:
      update_config:
        order: start-first
        
  db:
    image: postgres:17.2-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/database_password
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGUSER=${DATABASE_USERNAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - database_password

  web:
    image: ghcr.io/kapobajza/gimnazija_web:${GIT_COMMIT_HASH-prod}
    ports:
      - "3000"
    environment:
      - HOST=0.0.0.0
      - PUBLIC_GMNZ_API_URL=https://api.gimnazija-bug.ba
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`gimnazija-bug.ba`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    deploy:
      update_config:
        order: start-first


volumes:
  db-data:
  dashboard-uploads:

secrets:
  dashboard_jwt_secret:
    external: true
  dashboard_app_keys:
    external: true
  dashboard_api_token_salt:
    external: true
  dashboard_admin_jwt_secret:
    external: true
  dashboard_transfer_token_salt:
    external: true
  database_password:
    external: true