name: Prepare docker build
description: 'Prepares docker build'
runs:
  using: 'composite'
  steps:      
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: update docker metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: build

      - name: cache pnpm modules
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            pnpm
          key: pnpm-cache-${{ hashfiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-cache-

      - name: inject pnpm cache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "pnpm": "/pnpm/store"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
