name: Build and deploy Gimnazija dashboard strapi 

on:
  push:
    branches:
      - main
    paths:
      - 'dashboard/**/**.ts'
      - 'dashboard/package.json'
      - '!dashboard/README.md'

jobs:
  deploy_api:
    uses: ./.github/workflows/deploy.yaml
    with:
      service: api
      dockerfile_dir: dashboard
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}